### ISSUE TITLE
[REQUEST] Set log level in Docker Compose

### ISSUE THREAD

**Issue by Feriman22** [garethflowers/docker-ftp-server#107]
Currently the vsftpd in my environment generates a TON of log and I'd like to reduce it.

Please add a way to set the log parameters of vsftpd by setting a variable in Docker Compose, something like that:

```
services:
    ftp-server:
        container_name: my-ftp-server
        environment:
            - PUBLIC_IP=192.168.0.1
            - FTP_PASS=123
            - FTP_USER=user
            - xferlog_enable=YES
            - xferlog_std_format=NO
            - log_ftp_protocol=YES
        image: garethflowers/ftp-server
        ports:
            - "20-21:20-21/tcp"
            - "40000-40009:40000-40009/tcp" # For passive mode
        volumes:
            - "/data:/home/user"
```

It can be configured in `/etc/vsftpd/vsftpd.conf` file:

```
# This is by default YES
xferlog_enable=YES

# This was changed from default YES to NO.
# This was actually the setting preventing from logging properly.
xferlog_std_format=NO

# Enable verbose logging
log_ftp_protocol=YES
```

Thanks!
