### ISSUE TITLE
227 Entering Passive Mode (0,0,0,0,156,64).

### ISSUE THREAD

**Issue by AnhDai1997** [garethflowers/docker-ftp-server#88]
i create ftp server with this docker compose:
services:
  ftp-server:
    container_name: ftp-server
    environment:
      - FTP_PASS=<my - pass>
      - FTP_USER=anhdai
    image: garethflowers/ftp-server
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - './data:/home/anhdai'
 
but get error when try login from windows
![Screenshot 2024-04-12 154656](https://github.com/garethflowers/docker-ftp-server/assets/49276369/b3ca21c0-3a92-4a23-bccc-6add010fc52f)

this ftp server log:
![Screenshot 2024-04-12 154439](https://github.com/garethflowers/docker-ftp-server/assets/49276369/b6655909-a41f-4ab3-8cd8-314cd8d466f0)

how to fix this?

**Comment by galiullinis** [comment]
Hi! 
Mount your own vsftpd.conf file:

>     volumes:
>      - './data:/home/anhdai'
>      - './vsftpd.conf:/etc/vsftpd.conf'

where you can change the next few params:
> pasv_address=<your-external-IP-address-here-not-0.0.0.0>
> pasv_addr_resolve=NO

cause your FTP server tells to your PC FTP client to connect to 0.0.0.0 so why you need to specify correct external IP address

**Comment by poliyka** [comment]
> Hi! Mount your own vsftpd.conf file:
> 
> > ```
> > volumes:
> >  - './data:/home/anhdai'
> >  - './vsftpd.conf:/etc/vsftpd.conf'
> > ```
> 
> where you can change the next few params:
> 
> > pasv_address=<your-external-IP-address-here-not-0.0.0.0>
> > pasv_addr_resolve=NO
> 
> cause your FTP server tells to your PC FTP client to connect to 0.0.0.0 so why you need to specify correct external IP address

I tried it, but it gets stuck in the 'compose up' process and returns exit code 2. 
Therefore, I customized a Dockerfile to copy it into the container again
like this:

```yaml
# docker-compose.yaml
services:
  ftp-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FTP_PASS=pass
      - FTP_USER=user
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp' # Only needed for passive mode
    volumes:
      - './data:/home/user'
    network_mode: "bridge"
```

```dockerfile
# Dockerfile
FROM garethflowers/ftp-server

COPY [ ".//vsftpd.conf", "/etc" ]
```

And it work!
